"""Sync the duckdb floor line in requirements.txt from the SSOT (config/lambda/ducklake/version.yaml).

Usage:
  bin/venv-python -m scripts.sync.ducklake_version          # rewrite mode (idempotent)
  bin/venv-python -m scripts.sync.ducklake_version --check  # exit non-zero if drift detected

The duckdb line in requirements.txt is DERIVED from the SSOT version. This script keeps it in sync.
The floor pattern (>=<pin>) is preserved (not an exact pin) per human decision 2026-06-25.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
REQUIREMENTS_PATH = ROOT / "requirements.txt"


def _get_pinned_version() -> str:
    """Read the pinned version from the SSOT (avoids importing ducklake_version at module scope)."""
    import importlib.util  # noqa: PLC0415

    spec = importlib.util.spec_from_file_location(
        "src.common.ducklake_version",
        ROOT / "src" / "common" / "ducklake_version.py",
    )
    if not (spec and spec.loader):
        raise RuntimeError(f"Cannot load src.common.ducklake_version from {ROOT / 'src' / 'common' / 'ducklake_version.py'}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    return mod.pinned_duckdb_version()


_FLOOR_COMMENT = (
    "generated by scripts/sync/ducklake_version.py"
    " from config/lambda/ducklake/version.yaml;"
    " enforced by the ducklake-version-lockstep validate gate"
)


def _expected_floor_line(version: str) -> str:
    return f"duckdb>={version}  # {_FLOOR_COMMENT}"


# Matches the duckdb floor line with any version (including inline comment); also catches exact pins (==).
_DUCKDB_LINE_RE = re.compile(r"^duckdb[><=!]+[^\s#]*.*$", re.MULTILINE)


def sync(check_only: bool = False, requirements_path: Path | None = None) -> bool:
    """Sync the duckdb floor in requirements.txt.

    Returns True if the file is already in sync (or was successfully rewritten).
    Returns False (and exits non-zero in --check mode) if drift is detected.
    """
    req_path = requirements_path or REQUIREMENTS_PATH
    version = _get_pinned_version()
    expected_line = _expected_floor_line(version)

    content = req_path.read_text(encoding="utf-8")

    # Extract just the version token from the existing line for comparison
    # (tolerates inline comments and any operator)
    match = _DUCKDB_LINE_RE.search(content)
    if match:
        existing_line = match.group(0)
        existing_is_floor = existing_line.startswith(f"duckdb>={version}")
    else:
        existing_line = None
        existing_is_floor = False

    in_sync = existing_is_floor

    if in_sync:
        print(f"sync_ducklake_version: requirements.txt is in sync (duckdb>={version}). No change.")
        return True

    if check_only:
        if match:
            print(
                f"sync_ducklake_version: DRIFT DETECTED -- requirements.txt has {existing_line!r}, "
                f"expected floor duckdb>={version}. Run without --check to fix."
            )
        else:
            print(
                f"sync_ducklake_version: DRIFT DETECTED -- no duckdb line found in requirements.txt. "
                f"Expected floor duckdb>={version}."
            )
        return False

    if match:
        new_content = _DUCKDB_LINE_RE.sub(expected_line, content, count=1)
    else:
        new_content = content.rstrip("\n") + f"\n{expected_line}\n"

    req_path.write_text(new_content, encoding="utf-8")
    print(f"sync_ducklake_version: rewrote duckdb floor to duckdb>={version} in {req_path}.")
    return True


def main(argv: list[str] | None = None) -> int:
    import argparse  # noqa: PLC0415

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Exit non-zero if requirements.txt drifts from the SSOT")
    args = parser.parse_args(argv)

    ok = sync(check_only=args.check)
    return 0 if ok else 1


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
