"""Tests for scripts.checks.structural._classify -- the classification + measurement
engine (SGE-01/SGE-02/SGE-04, Decision 166). Every test runs against an INJECTED root
(tmp_path), never the live tree.
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import patch

from scripts.checks.structural import _classify

_REGISTRY_YAML = """\
schema_version: 1
exclusions:
  suffixes: [".py", ".md"]
  dirs: [pip, lambda-packages, docker, .venv, node_modules, .git, personal_scripts]
generated_pinned:
  - config/pinned_no_banner.yaml
classes:
  - slug: generated
    include: []
    governed: false
    unit: n/a
    limit: n/a
    max_line_chars: n/a
  - slug: config
    include: ["config/*.yaml", "config/*.yml"]
    governed: true
    unit: effective-lines
    limit: 500
    max_line_chars: 2000
  - slug: terraform
    include: ["terraform/*.tf"]
    governed: true
    unit: effective-lines
    limit: 500
    max_line_chars: 2000
  - slug: roadmaps
    include: ["docs/ROADMAP-*.yaml", "docs/ROADMAP-*.yml"]
    governed: true
    unit: effective-lines
    limit: 500
    max_line_chars: 2000
    defer_to_incumbent:
      docs/ROADMAP-PLATFORM.yaml:
        incumbent: validate_platform_roadmap
        authorized_by: dec-166
  - slug: residual
    include: []
    governed: true
    unit: effective-lines
    limit: 500
    max_line_chars: 2000
budgets: {}
long_line_budgets: {}
"""


def _write_registry(tmp_path: Path) -> None:
    config_dir = tmp_path / "config"
    config_dir.mkdir(exist_ok=True)
    (config_dir / "structural_size_budgets.yaml").write_text(_REGISTRY_YAML, encoding="utf-8")


def _clear_cache() -> None:
    _classify._registry_cache.clear()


class TestClassifyPath:
    def test_first_match_wins_provenance_before_location(self, tmp_path: Path) -> None:
        """A generated file INSIDE a hand-authored, governed directory classifies by
        provenance (the banner), not by its directory+extension glob location."""
        _write_registry(tmp_path)
        config_dir = tmp_path / "config"
        banner_file = config_dir / "auto.yaml"
        banner_file.write_text("# GENERATED -- DO NOT EDIT (scripts/foo.py)\nkey: value\n", encoding="utf-8")

        _clear_cache()
        with patch("scripts.checks._common.ROOT", tmp_path):
            assert _classify.classify_path("config/auto.yaml") == "generated"

    def test_both_yaml_and_yml_spellings_match(self, tmp_path: Path) -> None:
        _write_registry(tmp_path)
        _clear_cache()
        with patch("scripts.checks._common.ROOT", tmp_path):
            assert _classify.classify_path("config/probe.yaml") == "config"
            assert _classify.classify_path("config/probe.yml") == "config"

    def test_residual_default_for_unmatched_extension(self, tmp_path: Path) -> None:
        _write_registry(tmp_path)
        _clear_cache()
        with patch("scripts.checks._common.ROOT", tmp_path):
            assert _classify.classify_path("some/new/surface.hcl2") == "residual"

    def test_suffix_exclusion_wins_before_provenance_or_classes(self, tmp_path: Path) -> None:
        _write_registry(tmp_path)
        _clear_cache()
        with patch("scripts.checks._common.ROOT", tmp_path):
            assert _classify.classify_path("config/README.md") == "excluded"

    def test_vendored_dir_exclusion(self, tmp_path: Path) -> None:
        _write_registry(tmp_path)
        _clear_cache()
        with patch("scripts.checks._common.ROOT", tmp_path):
            assert _classify.classify_path("config/.venv/site-packages/foo.yaml") == "excluded"

    def test_narrow_banner_regex_does_not_match_bare_prose_mention(self, tmp_path: Path) -> None:
        """A loose regex over-matched audits/size-governance-expansion-3dee4a5.yaml and
        docs/plans/PLAN-dcg-decisions-index.yaml on the bare word 'generated' in prose --
        this narrow banner must not repeat that defect."""
        _write_registry(tmp_path)
        config_dir = tmp_path / "config"
        prose_file = config_dir / "prose.yaml"
        prose_file.write_text("# This registry was generated by a human, not a machine.\nkey: value\n", encoding="utf-8")

        _clear_cache()
        with patch("scripts.checks._common.ROOT", tmp_path):
            assert _classify.classify_path("config/prose.yaml") == "config"

    def test_generated_pinned_outranks_missing_banner(self, tmp_path: Path) -> None:
        _write_registry(tmp_path)
        config_dir = tmp_path / "config"
        pinned_file = config_dir / "pinned_no_banner.yaml"
        pinned_file.write_text("key: value\n" * 600, encoding="utf-8")

        _clear_cache()
        with patch("scripts.checks._common.ROOT", tmp_path):
            assert _classify.classify_path("config/pinned_no_banner.yaml") == "generated"

    def test_roadmap_platform_deferred_roadmap_product_included(self, tmp_path: Path) -> None:
        _write_registry(tmp_path)
        _clear_cache()
        with patch("scripts.checks._common.ROOT", tmp_path):
            assert _classify.classify_path("docs/ROADMAP-PLATFORM.yaml") == "roadmaps"
            assert _classify.classify_path("docs/ROADMAP-PRODUCT.yaml") == "roadmaps"
            reg = _classify.load_registry()
            roadmaps_row = next(r for r in reg["classes"] if r["slug"] == "roadmaps")
            assert "docs/ROADMAP-PLATFORM.yaml" in roadmaps_row["defer_to_incumbent"]
            assert "docs/ROADMAP-PRODUCT.yaml" not in roadmaps_row["defer_to_incumbent"]


class TestCountingRule:
    def test_comment_line_not_counted(self) -> None:
        text = "# a comment\nkey: value\n"
        assert _classify.effective_lines(text) == 1

    def test_blank_line_not_counted(self) -> None:
        text = "key: value\n\n\nother: value\n"
        assert _classify.effective_lines(text) == 2

    def test_double_slash_line_in_tf_is_counted_no_per_language_cleverness(self) -> None:
        """The pinned rule applies verbatim to every class -- a `//` line in .tf IS
        counted (no per-language comment handling)."""
        text = 'resource "aws_iam_role" "x" {\n  // this looks like a comment in some languages\n}\n'
        assert _classify.effective_lines(text) == 3

    def test_longest_line(self) -> None:
        text = "short\n" + ("x" * 2500) + "\nshort\n"
        assert _classify.longest_line(text) == 2500


class TestIterMeasuredFiles:
    def test_excludes_defer_to_incumbent_and_exempt_classes(self, tmp_path: Path) -> None:
        _write_registry(tmp_path)
        (tmp_path / "docs").mkdir()
        (tmp_path / "docs" / "ROADMAP-PLATFORM.yaml").write_text("key: value\n", encoding="utf-8")
        (tmp_path / "docs" / "ROADMAP-PRODUCT.yaml").write_text("key: value\n", encoding="utf-8")
        (tmp_path / "terraform").mkdir()
        (tmp_path / "terraform" / "main.tf").write_text("resource {}\n", encoding="utf-8")

        tracked = ["docs/ROADMAP-PLATFORM.yaml", "docs/ROADMAP-PRODUCT.yaml", "terraform/main.tf"]

        def _fake_run(cmd, **kwargs):
            from unittest.mock import MagicMock

            result = MagicMock()
            result.returncode = 0
            result.stdout = "".join(f"{p}\n" for p in tracked)
            return result

        _clear_cache()
        with patch("scripts.checks._common.ROOT", tmp_path), patch("scripts.checks._common.run", _fake_run):
            measured = dict(_classify.iter_measured_files())

        assert "docs/ROADMAP-PLATFORM.yaml" not in measured
        assert measured.get("docs/ROADMAP-PRODUCT.yaml") == "roadmaps"
        assert measured.get("terraform/main.tf") == "terraform"

    def test_excluded_and_phantom_tracked_paths_are_skipped(self, tmp_path: Path) -> None:
        """A suffix-excluded tracked file (README.md) is skipped by the excluded-slug
        branch; a tracked path git ls-files reports that no longer exists on disk (a
        phantom/stale snapshot entry) is skipped without error; a tracked file that
        classifies into a non-governed (exempt) class is skipped too."""
        _write_registry(tmp_path)
        (tmp_path / "config" / "README.md").write_text("# docs\n", encoding="utf-8")
        (tmp_path / "terraform").mkdir()
        (tmp_path / "terraform" / "main.tf").write_text("resource {}\n", encoding="utf-8")
        (tmp_path / "config" / "pinned_no_banner.yaml").write_text("key: value\n", encoding="utf-8")

        tracked = [
            "config/README.md",
            "terraform/main.tf",
            "terraform/deleted.tf",
            "config/pinned_no_banner.yaml",
        ]

        def _fake_run(cmd, **kwargs):
            from unittest.mock import MagicMock

            result = MagicMock()
            result.returncode = 0
            result.stdout = "".join(f"{p}\n" for p in tracked)
            return result

        _clear_cache()
        with patch("scripts.checks._common.ROOT", tmp_path), patch("scripts.checks._common.run", _fake_run):
            measured = dict(_classify.iter_measured_files())

        assert "config/README.md" not in measured
        assert "terraform/deleted.tf" not in measured
        assert "config/pinned_no_banner.yaml" not in measured
        assert measured.get("terraform/main.tf") == "terraform"
